### ISSUE TITLE
Host data on an external data repository

### ISSUE THREAD

**Issue by niksirbi** [SainsburyWellcomeCentre/NeuralPlayground#41]
The GitHub repository currently occupies ~650 MB, mainly due to hosting data. `git` is not well suited for large data storage.

Some possibilities:
- [GIN](https://gin.g-node.org)
- [Zenodo](https://zenodo.org/)

From @atyson:
> We can then either implement our own solution for downloading data (e.g. https://github.com/brainglobe/bg-atlasapi) or use an existing tool such as [pooch](https://www.fatiando.org/pooch/latest/) or possibly a more involved data-management solution such as [DataLad](https://www.datalad.org/) (this may be overkill though).

**Comment by adamltyson** [comment]
One thing to think about at this early stage is whether or not it's worth re-writing the git history. Even if the data is hosted elsewhere, the git repo will stay the same size. Even on a fast university connection, `git clone` takes an annoyingly long time.

**Comment by adamltyson** [comment]
I've created a [GIN repository](https://gin.g-node.org/neuroinformatics/NeuralPlayground) which could be used to host this data. We use it for all data associated with the [BrainGlobe](https://github.com/brainglobe) project and it works well. I can give everyone access if you create a GIN login.

Before the data can be moved, do we have details on the licensing for the three initial datasets? Both to see if we can indeed host them ourselves, but also to determine which license we can use going forward.
