### ISSUE TITLE
Speed up tests

### ISSUE THREAD

**Issue by niksirbi** [SainsburyWellcomeCentre/NeuralPlayground#71]
The tests currently take a long time to run on CI. It could be because the test data is downloaded online every time the tests start. This is not an issue for local tests because `pooch` caches the data locally. 

Maybe there is a way to similarly fetch and cache the data during GitHub actions, and reuse it across the test matrix,

**Comment by adamltyson** [comment]
See e.g.:
https://github.com/brainglobe/brainglobe-napari/blob/8598161e49f995ebd0e765de3ef4c65f001dfe8f/.github/workflows/test_and_deploy.yml#L57-L63

**Comment by niksirbi** [comment]
Amazing, this seems quite straightforward
